### ISSUE TITLE
CustomServer.Announce in .conf doesn't work

### ISSUE THREAD

**Issue by andoys** [azerothcore/mod-fireworks-on-level#3]
Azerothcore rev. ded199d

This setting doesn't work. i set it to 0
CustomServer.Announce = 0

and it still shows up.

**Comment by milestorme** [comment]
Thank you again bro , I’ll take a look at this one too

**Comment by milestorme** [comment]
Fixed in  https://github.com/azerothcore/mod-fireworks-on-level/pull/4, let me know
